### ISSUE TITLE
weeks 1-5 - Grading

### ISSUE THREAD

**Issue by satenikmnatsakanyan-aua** [davidmamyan20/ENGS115-2021-David-Mamyan#1]
Summary +9
HW1 +
HW2 +
HW3 +
HW4 +
Quiz1 +3
----------
HW submission names - try to put meaningful names to the files
--------

Week 1-5 Total (19%): 14.45
Participation (3%): 2.45
HW 1-4 (10%): 10
Quiz1 (6%): 2.00

**Comment by davidmamyan20** [comment]
I just added HW1, Ok I will work on the names to the files

**Comment by satenikmnatsakanyan-aua** [comment]
David jan, adding HW1 now means a very-very late submission.

**Comment by davidmamyan20** [comment]
Ms Satenik jan I did add in the old repository earlier on time, but sorry for submitting here too late

**Comment by satenikmnatsakanyan-aua** [comment]
I see, please also post the old link here

**Comment by davidmamyan20** [comment]
Sure)))) https://github.com/davidmamyan20/ENGS-110-2021-Homeworks

**Comment by satenikmnatsakanyan-aua** [comment]
thanks !

**Comment by davidmamyan20** [comment]
Received
