### ISSUE TITLE
Week 6-10

### ISSUE THREAD

**Issue by satenikmnatsakanyan-aua** [davidmamyan20/ENGS115-2021-David-Mamyan#2]
Participation%: 3

Quiz#2-Day1: 1.5
Quiz#2-Day2: 4
Quiz#2-Day3-Code: 0 Does not compile - need to talk
Quiz#2-Day4-Retake: 4

Quiz%: 5.1

HW5: 0
HW6: 1
HW7: 0
HW8: 0
HW9: 1

HW%: 8

Week6-10%: 14.1
@davidmamyan20

**Comment by davidmamyan20** [comment]
Ms Satenik 

I have question, you told us there was no need to write summaries after the week 6. So that's why I didn't write. Do I have to correct them??

**Comment by davidmamyan20** [comment]
Dear Ms Satenik
 I wrote the summaries and commited to my github repository in the summary folder, the file name is Summaryweek610. You can check them
